image: node:20

pipelines:
  default:
    - step:
        name: Week1 - Build & Test
        caches:
          - node
        script:
          - echo "Starting Week1 CI"
          - cd week1
          - node --version && npm --version
          - npm ci || npm install
          - npm test -- --run || echo "No tests configured"
          - npm run build
    - step:
        name: Week1 API - Build & Test
        caches:
          - node
        script:
          - echo "Backend CI"
          - cd week1-api
          - node --version && npm --version
          - npm ci || npm install
          - npm test -- --run || echo "No backend tests configured"
          - npm run build

  branches:
    main:
      - step:
          name: Main - Week1 Build & Test
          caches:
            - node
          script:
            - echo "Main branch CI for Week1"
            - cd week1
            - node --version && npm --version
            - npm ci || npm install
            - npm test -- --run || echo "No tests configured"
            - npm run build
      - step:
          name: Main - Week1 API Build & Test
          caches:
            - node
          script:
            - echo "Main branch CI for Week1 API"
            - cd week1-api
            - node --version && npm --version
            - npm ci || npm install
            - npm test -- --run || echo "No backend tests configured"
            - npm run build
