[build]
  command = "npm run build"
  publish = "dist"

# Local dev proxy (optional)
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
